spring:
  datasource:
    url: jdbc:mysql://mysql:3306/skyisthelimit
    username: root
    password: Dlrpskdi77@

  jpa:
    hibernate:
      ddl-auto: create

cors:
  allowed-origins: "https://www.acmicpc.net"

swagger:
  server-url: http://localhost:8081