spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/skyisthelimit?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: Dlrpskdi77@

  jpa:
    hibernate:
      ddl-auto: create

cors:
  allowed-origins: "https://www.acmicpc.net"

swagger:
  server-url: http://141.164.34.245:8080