name: Deploy Prod Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: make application.yml
        if: contains(github.ref,'main')
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          
          cat <<EOF > application.yml
          ${{ secrets.APPLICATION_YML }}
          EOF
          
          cat <<EOF > application-prod.yml
          ${{ secrets.APPLICATION_PROD_YML }}
          EOF

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: southernlight3816
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=southernlight3816/skyisthelimit-prod:latest
          docker build -t skyisthelimit-prod .
          docker tag skyisthelimit-prod $IMAGE_NAME
          docker push $IMAGE_NAME

      - name: Deploy to VULTR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_PROD_HOST }}
          username: ${{ secrets.VULTR_USERNAME }}
          password: ${{ secrets.VULTR_PROD_PASSWORD }}

          script: |
            docker login -u southernlight3816 -p ${{ secrets.DOCKER_PASSWORD }}
            cd ~/skyisthelimit
            
            docker compose down
            docker compose pull springboot
            docker compose up -d